---
pkg_versions:
  java:
    version: 21.0.6
    build: 7
    os_families: ["Darwin", "Debian"]
  idea:
    version_full: 252.26199.169
    version: 2025.2.2
    os_families: ["Darwin", "Debian"]
    wsl: false
    dev_container: false
  rider:
    version: 2025.2.2
    os_families: ["Debian"]
    wsl: false
    dev_container: false
  localsend:
    version: 1.17.0
    os_families: ["Darwin"]
    wsl: false
    dev_container: false
  yubico_authenticator:
    version: 7.1.2
    os_families: ["Darwin"]
    wsl: false
    dev_container: false
  fzf:
    version: 0.60.3
    os_families: ["Darwin", "Debian"]
  nerdfonts:
    version: 3.4.0
    os_families: ["Darwin", "Debian"]
    wsl: false
    dev_container: false
  go:
    version: 1.24.0
    os_families: ["Darwin", "Debian"]
  node:
    version: 24.7.0
    os_families: ["Darwin", "Debian"]
  scala:
    version: 3.5.1
    os_families: ["Darwin", "Debian"]
  sbt:
    version: 1.10.10
    os_families: ["Darwin", "Debian"]
  maven:
    version: 3.9.12
    os_families: ["Darwin", "Debian"]
  gradle:
    version: 8.13
    os_families: ["Darwin", "Debian"]
  cmake:
    version: 4.2.1 
    os_families: ["Darwin", "Debian"]
  bazelisk:
    version: 1.22.0
    os_families: ["Darwin", "Debian"]
  tofu:
    version: 1.9.1
    os_families: ["Darwin", "Debian"]
  macports:
    version: 2.10.5-15
    os_families: ["Darwin"]
  alacritty:
    version: 0.15.1
    os_families: ["Darwin", "Debian"]
    wsl: false
    dev_container: false
  ruby:
    version: 3.4.7
    os_families: ["Darwin", "Debian"]
  debian:
    release: trixie
    version: 13
    build: 20250924-2245
    os_families: ["Debian"]
    wsl: false
    dev_container: false
  docker:
    version: 184744
    os_families: ["Darwin", "Debian"]
    wsl: false
    dev_container: false
  mysql:
    version: 8.0.41
    major: 8.0
    os_families: ["Darwin", "Debian"]
    os:
      darwin: macos15
      debian: linux-glibc2.28
  wasabi:
    version: 2.6.0
    os_families: ["Darwin"]
    wsl: false
    dev_container: false
  ollama:
    version: 0.11.10
    os_families: ["Darwin", "Debian"]
    wsl: false
    dev_container: false
  kubectl:
    version: 1.33.1
    os_families: ["Darwin", "Debian"]
  zig:
    version: 0.16.0-dev.1634+b27bdd5af
    os_families: ["Debian"]
  zig14:
    version: 0.14.1
    os_families: ["Debian"]
  zig15:
    version: 0.15.2
    os_families: ["Debian"]
  ghostty:
    version: 1.2.3
    os_families: ["Darwin", "Debian"]
    wsl: false
    dev_container: false
