---
macports_packages:
  - coreutils
  - gnupg2
  - bash
  - jq
  - libyaml
  - openssh +fido2
  - pinentry-mac
  - rsync
  - ruby-build
  - swig
  - swig-python
  - the_silver_searcher
  - tree
  - aria2
  - universal-ctags
  - htop
  - ImageMagick
  - podman
